spring:
  application:
    name: iptv-manager

  profiles:
    active: dev

  datasource:
    driver-class-name: org.sqlite.JDBC

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  mapper-locations: classpath:mapper/*.xml

quartz:
  job-store-type: memory
  properties:
    org:
      quartz:
        scheduler:
          instanceName: IPTVManagerScheduler
          instanceId: AUTO
          threadName: IPTVManagerQuartzThread
        jobStore:
          class: org.quartz.simpl.RAMJobStore
        threadPool:
          class: org.quartz.simpl.SimpleThreadPool
          threadCount: 5
          threadPriority: 5
          threadsInheritContextClassLoaderOfInitializingThread: true

server:
  port: 8080

logging:
  level:
    root: INFO
    com.lemongo97.iptv.iptvmanager: DEBUG
    com.lemongo97.iptv.iptvmanager.mapper: TRACE

---
# 开发环境 - 内存数据库（稳定）
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: "jdbc:sqlite:backend/tmp/iptv.db"
  liquibase:
    enabled: true
    change-log: classpath:db/changelog.yml

---
# 生产环境 - 文件数据库
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: "jdbc:sqlite:iptv.db"
  liquibase:
    enabled: true
    change-log: classpath:db/changelog.yml
